src/levels/mixed/jugglingCommits.js
Fixes #233.
Thanks to @maxing80 for catching it :)
=> amend was mispelled in Spanish version of mixed2

src/levels/mixed/grabbingOneCommit.js
=> Update grabbingOneCommit.js - fix typo error

src/levels/remote/pushManyFeatures.js
=> fix typo bran->branch

src/levels/intro/merging.js
Change the "re-display this dialog with \"help level\"!" with "objective" instead
=> Update french translation for merging intro level

src/js/intl/strings.js, src/levels/mixed/grabbingOneCommit.js, src/levels/mixed/tags.js, src/levels/rampup/interactiveRebase.js, src/levels/rampup/relativeRefs2.js, src/levels/rampup/reversingChanges.js, src/levels/rebase/selectiveRebase.js, src/levels/remote/clone.js, src/levels/remote/fakeTeamwork.js, src/levels/remote/fetch.js, src/levels/remote/fetchArgs.js, src/levels/remote/fetchRebase.js, src/levels/remote/mergeManyFeatures.js, src/levels/remote/pull.js, src/levels/remote/pullArgs.js, src/levels/remote/push.js, src/levels/remote/pushArgs.js, src/levels/remote/pushArgs2.js, src/levels/remote/pushManyFeatures.js, src/levels/remote/remoteBranches.js, src/levels/remote/sourceNothing.js, src/levels/remote/tracking.js
My contribution to this incredibly useful project!
=> Fixing French typos and awkward translations

src/levels/rebase/manyRebases.js
Probably a left-over from translating.
=> Remove superfluous english sentence from german translation

src/js/intl/strings.js, src/levels/intro/branching.js, src/levels/mixed/grabbingOneCommit.js, src/levels/mixed/tags.js, src/levels/rampup/relativeRefs2.js
* Added missing levels names
* Fixed typos
=> Fixes in Russian traslation

README.md, src/levels/remote/pull.js
I have added ru_RU (Russian) translation for the "pull.js" lesson. With approval of project owner I added my account name into list of contributors.
=> Added ru_RU (Russian) translation for the "pull.js".

src/levels/remote/pushArgs2.js
New russian's translation for Git push arguments lesson number 2
=> Added ru_RU (Russian) translation for the "Git push arguments -- Expanded!" lesson

src/levels/rampup/detachedHead.js
translated detachedHead.js in korean
I am trying to start translating the rest of the application into korean because this beautiful tutorial is not translated completely in korean
please let me know if there is something I have to be aware of.
=> translated detachedHead.js in korean

src/js/dialogs/sandbox.js, src/levels/intro/branching.js
Fix typo for french translation
=> Fix typo in french translation

src/levels/mixed/describe.js, src/levels/mixed/tags.js, src/levels/rampup/cherryPick.js, src/levels/rampup/interactiveRebase.js
also fixed indentations you mentioned.
=> Translated tags.js & describe.js into Korean

src/js/intl/strings.js, src/js/views/levelDropdownView.js
Now it's possible to locale "Main" and "Remote" tabs.
=> Add 'uk' and 'ru_RU' translations of the level bar tabs

src/levels/rampup/interactiveRebase.js
=> Fixed typo in german translation

src/js/intl/strings.js
Add korean translations.
Please check it.
=> Add korean translations

__tests__/remote.spec.js, src/js/git/commands.js, src/js/graph/treeCompare.js, src/js/level/disabledMap.js, src/js/level/index.js, src/js/sandbox/index.js, src/js/util/errors.js, src/js/visuals/visTag.js, src/js/visuals/visualization.js, todo.txt
=> English typos in comments and strings

Gruntfile.js
=> Fixed #392

README.md
I actually tried to clone an existing repository after reading the current description. Hopefully this makes it clearer that the command is LGB-specific and meant to be used without any arguments.
=> README: clarify that git clone is still demo

src/levels/mixed/jugglingCommits.js, src/levels/rampup/relativeRefs.js, src/levels/rampup/relativeRefs2.js, src/levels/remote/fetch.js, src/levels/remote/fetchRebase.js, src/levels/remote/remoteBranches.js
I fixed some typos in the German translation. 588268e is not a typo by itself but a minor correction :)
If you want me to squash those commits (has happened on other repos), I can do that.
=> Fix German translation

src/template.index.html
Sorry, this was bothering the grammar Nazi inside me :-)
=> Correct a -> an in og:description

LICENSE, LICENSE.md
Fix line break to make it easier to read.
**Current**
**Suggestion**
It's the same license, but you don't need to scroll to read.
=> Improve readability

src/levels/mixed/describe.js
=> Fix typo in french

src/js/app/index.js, src/template.index.html
According to [Google documentation](https://support.google.com/webmasters/answer/182192?hl=en) this doesn't change much, as google won't look at this attributes, but it may be helpfull for less sophisticated search engines.
=> Set html lang and meta http-equiv="content-language" attr on language change

src/levels/rampup/reversingChanges.js, src/levels/remote/pushArgs.js, src/levels/remote/pushArgs2.js
Even after reading the Pro Git book you learned me something :)
just found a few typos :pencil: 
PS It wasn't exactly clear to me how or to what extent the levels remember your progress?
=> A few English typos

__tests__/base.js, __tests__/remote.spec.js, src/js/app/index.js, src/js/commands/index.js, src/js/git/commands.js, src/js/git/headless.js, src/js/git/index.js, src/js/graph/treeCompare.js, src/js/level/builder.js, src/js/level/index.js, src/js/level/parseWaterfall.js, src/js/models/commandModel.js, src/js/util/eventBaton.js, src/js/views/builderViews.js, src/js/views/gitDemonstrationView.js, src/js/visuals/index.js, src/js/visuals/visBase.js, src/js/visuals/visBranch.js, src/js/visuals/visNode.js, src/js/visuals/visTag.js, src/js/visuals/visualization.js, todo.txt
=> Fixed typos in comments and strings

README.md
updated the readme.md file and corrected some grammatical mistakes. Added more lines to increase clarity.
=> corrected grammatical error in readme.md

src/levels/rampup/interactiveRebase.js
Hi,
One of my student noted an issue in the french translation. Here is the fix.
Cheers,
Daniel
=> Fix french translation

src/levels/index.js
Another small typo found in the french translation.
=> Yet another small french typo fix

src/template.index.html
Update the "helperText" for better clarity
=> A little change in "helperText" of the "pick" button (rebase -i)

src/style/main.css
Generally it is a good idea to disable button text selection, however I am not sure if it is true for this app. What do you think?
=> Make button text unselectable

src/levels/mixed/describe.js
HI, I tried to improve description of git describe somehow.
=> see #543 refined explanation of git describe

src/js/intl/strings.js
Update translation of "Show Goal" and "Hide Goal".
=> Update German translation

src/js/sandbox/commands.js
=> Refactor show commands to extract keys from the object

package.json
`contributor-faces` is a package to build `README.md`, not require in code so we need to change it from `dependencies` to `devDependencies`
=> chore(deps): `contributor-faces` to `devDepen`

README.md
Hide `[//]: contributor-faces` in `README.md`
=> fix(readme): hide comment in README.md

.travis.yml
=> Update test in travis-ci

README.md
=> Update README reference from npm to yarn

src/style/main.css
=> Set line height of icons bar icons

src/levels/remote/fetchArgs.js, src/levels/remote/pushArgs.js
Two small fixes in german texts
=> German Language Issues

src/levels/intro/merging.js, src/levels/intro/rebasing.js, src/levels/rampup/interactiveRebase.js, src/levels/remote/clone.js, src/levels/remote/fakeTeamwork.js, src/levels/remote/fetch.js, src/levels/remote/fetchArgs.js, src/levels/remote/pushArgs.js, src/levels/remote/pushArgs2.js, src/levels/remote/remoteBranches.js, src/levels/remote/sourceNothing.js, src/levels/remote/tracking.js
Some typos detected in the **es_AR** (Argentinian) translation.
=> Various 'es_AR' translation typos

src/js/stores/LocaleStore.js
=> Other version of PR #624 -- map header directly from browser

src/levels/remote/pullArgs.js
=> [Fix] Fix typo in korean

yarn.lock
=> Fix some security issues in dependencies in yarn.lock

src/levels/remote/lockedMaster.js
Added Russian translation with slight design changes.
PS It was a good practical lesson :)))
=> Add RUS translate for "Locked Master" level

src/levels/remote/lockedMaster.js
Sorry, This is my first using github pull request. I missing  one ','  before  "zh_CN": {
I tested in virtalbox this time. please check it ,thansk!
=> Lockedmaster simple chinese zhcn translation.

src/levels/remote/lockedMaster.js
The spanish translation (es_ES) has been added for the `Locked master` level
=> Spanish translation of locked master level

src/levels/remote/lockedMaster.js
While I was learning to use git with this app, I found a level(lockedMaster) that has not been translated yet, so I translated it in Korean. :) this app helped me a lot!
=> Korean translation of lockedMaster.js

src/js/stores/LocaleStore.js
Add locale in `href`
If the user turns off the browser and opens it again, they keep their's locale
Oh, build have error(I cannot test in my local because I am attempting #654)
Wait for me fix this Travis error
=> [feat] update url if user change locale

src/js/stores/LevelStore.js
I know that you are very busy, just resolve your problem.
Recently, I create the chore pull request(not the important change) so you can temporarily ignore it in this time.
=> chore(test): mock `localStorage`

src/levels/intro/rebasing.js
Hi !
Thanks for this amazing git tutorial !
I've found a missing french translation into intro/rebasing, here it is (and at the same time my first PR :)
=> Fix missing french translation

src/levels/remote/lockedMaster.js
Hi,
Here is a french translation of the level "Remote 8 locked master". Other translations are missing, sorry I'm not qualified ;-)
=> add french translation to lockedMaster

gulpfile.js
I used to have a shell script for this but after #657 lets add an actual command for it!
this will only help me since only I have deploy permissions but still helpful as I'm transferring computers/systems constantly
=> Try to add deploy command to gulp

gulpfile.js
=> Using the production build of React

src/js/intl/strings.js
I noticed a typo in Korean translation, so I simply fixed it (line 1427)
Also, although most of the Korean translations are written in polite speech, few of them were written in informal speech, which were quite awkward. For consistency, I fixed them to polite speech.
=> korean translation typo revised & some improvement for polite speech

src/levels/remote/fetchRebase.js
Hello
just a little French translation correction
=> fetchRebase.js French translation correction

src/levels/remote/lockedMaster.js
I made some changes to the es_ES translation and added the es_AR one.
=> es_AR translation & es_ES corrections

package.json, yarn.lock
Resolves #682 and #681  for reference
=> Revert jquery back to 1.8 or above

gulpfile.js, package.json, src/js/views/rebaseView.js, yarn.lock
=> Woohoo, fix jquery UI

src/js/views/rebaseView.js
=> Add `draggable` of `jquery-ui`

src/js/dialogs/levelBuilder.js, src/js/intl/strings.js, src/levels/index.js, src/levels/rebase/manyRebases.js
fixed typos and improved the readability of some sentences
=> Improvements of the german translation

src/js/models/commandModel.js, src/js/sandbox/commands.js, src/js/stores/LevelStore.js
=> Resolves #593 -- add alias support with local storage

src/js/visuals/index.js, src/js/visuals/visBranch.js, src/js/visuals/visNode.js, src/js/visuals/visTag.js, src/style/main.css
Thanks for merging #726 in. I checked the result (on Windows) and realized I forgot to change the font family in `main.css` 😅.
=> #726 follow-up

src/js/git/commands.js
As discussed in #596 , git has added new "alternative" commands to `git checkout`, in particular `git switch`.
`git switch <branch>` is similar to `git checkout <branch>`.
The `-c` option has been added allowing to switch to a new branch, the result is similar to `git checkout -b <branch>`.
=> Added git switch with '-' and '-c' as optional arguments

src/js/dialogs/confirmShowSolution.js, src/js/dialogs/levelBuilder.js
First translations using _**'es_MX'**_ for i18n, for #hacktoberfest purpose.
Any comment or review is accepted.
I know that the repository does not have hacktoberfest enabled but I would love to contribute anyway and thus finish the challenge.
=> Adding support to Mexican Spanish Lang

src/js/dialogs/confirmShowSolution.js, src/js/dialogs/levelBuilder.js, src/js/dialogs/nextLevel.js, src/js/dialogs/sandbox.js, src/js/intl/strings.js, src/js/react_views/IntlHelperBarView.jsx, src/js/stores/LocaleStore.js, src/levels/index.js, src/levels/intro/branching.js, src/levels/intro/commits.js, src/levels/intro/merging.js, src/levels/intro/rebasing.js, src/levels/rebase/manyRebases.js, src/style/main.css
Currently, 4 first lessons translated, ie "Introduction Sequence"
I will try to translate all lessons as soon as possible.
=> [WIP] Polish translation

src/levels/intro/branching.js
=> Resolves #750 -- reference git switch

src/levels/intro/branching.js, src/style/main.css
I gave a new Polish translation for the new switch command.
ps. I made a link in HTML tags to add target="_ blank" to open in a new browser window... propose to do it in the original EN ... I also send PR #756 (either accept or reject) ;)
=> [PL]Translate new info - switch

src/js/dialogs/nextLevel.js, src/js/intl/strings.js, src/js/views/index.js, src/levels/rampup/detachedHead.js, src/levels/rampup/relativeRefs.js, src/levels/rampup/relativeRefs2.js, src/levels/rampup/reversingChanges.js
Moreover I added a translation for buttons
after passing a level
=> Another chunk of polish translation

src/levels/remote/tracking.js
Updating this label to match with other updates from `master` to `main`.
=> Update the label from totallyNotMaster to totallyNotMain

src/levels/rampup/interactiveRebase.js
Includes changes [proposed in #526](https://github.com/pcottle/learnGitBranching/issues/526#issuecomment-754570008), plus a couple other minor adjustments.
=> Clarify "pick" vs. "drop" in interactive rebase

src/js/dialogs/sandbox.js
Hi there! This fixes a really minor typo in all Spanish variants.
=> Fix spanish typo

src/levels/advanced/multipleParents.js, src/levels/index.js
Thanks for accepting the pull request.  Second batch of translations are added in this PR.
=> Tamil Translations

src/levels/mixed/describe.js, src/levels/mixed/grabbingOneCommit.js, src/levels/mixed/jugglingCommits.js, src/levels/mixed/jugglingCommits2.js, src/levels/mixed/tags.js, src/levels/rampup/interactiveRebase.js
Hey! Here it is another chunk of Polish translation. 
Have a nice day
=> Mixed chapter Polish translation

src/levels/advanced/multipleParents.js, src/levels/rebase/manyRebases.js, src/levels/rebase/selectiveRebase.js
I hope I can translate all remote too :)
=> All main chapters translated!

src/levels/remote/clone.js, src/levels/remote/remoteBranches.js
My Polish translations for two first levels from Push & Pull -- remote repositories. It's also my first pull request ever, I hope I did everything ok ;)
=> Polish translation for Clone Intro and Remote Branches levels

src/levels/rampup/reversingChanges.js
=> Fix translations in rampup/reversingChanges

src/levels/advanced/multipleParents.js, src/levels/intro/branching.js, src/levels/intro/merging.js, src/levels/intro/rebasing.js, src/levels/mixed/describe.js, src/levels/mixed/grabbingOneCommit.js, src/levels/mixed/jugglingCommits.js, src/levels/mixed/jugglingCommits2.js, src/levels/mixed/tags.js, src/levels/rampup/cherryPick.js, src/levels/rampup/detachedHead.js, src/levels/rampup/interactiveRebase.js, src/levels/rampup/relativeRefs.js, src/levels/rampup/relativeRefs2.js, src/levels/rampup/reversingChanges.js, src/levels/rebase/manyRebases.js, src/levels/rebase/selectiveRebase.js
As promised, all local levels. I did not have enough knowledge yet about remote. I'll come back.
I ask here to not open issues (maybe I've missed them): 
1. command `locale`, is not shown in `show commands`
2. I've not found a list of all languages
3. I've build and tested, once I open the index.html file it starts with `index.html?locale=it_IT`, I've messed up or is the correct behavior? (like it detects my country or dunno)
this close #811
=> Italian transl

src/style/main.css
Hi @pcottle
Long time no see :)
This reverts commit e110bcedd0951587801490a344e90d542a779c13.(#794)
Fixed #817
We must use another way to fix that bug (I don't know what is that bug)
=> Revert "Fix image display in the goal popup"

src/levels/mixed/jugglingCommits2.js, src/levels/rampup/reversingChanges.js
Nothing spectacular. Let me know what you think. :)
=> Small improvements to German translation

src/levels/remote/lockedMain.js
I found Locked Main level didn't have the zh_TW version, so I translated it.
Thank you for the amazing App.
=> fix: add zh_TW translation

src/js/sandbox/commands.js
=> Issue #845 -- show options for each command: Resolves #845

src/levels/remote/fetchArgs.js, src/levels/remote/pullArgs.js, src/levels/remote/pushArgs2.js, src/levels/remote/sourceNothing.js
I have translated following contents into japanese.
- remote/pushArg2.js
- remote/fetchArgs.js
- remote/sourceNothing.js
- remote/pullArgs.js
=> Translate several contents into Japanese

src/levels/rampup/reversingChanges.js
Thanks for considering. Great project.
=> changed "reverts" to "reverses" for readability and consistency 

src/js/intl/strings.js
I add some bottom menu "zh_TW" translations
=> Add bottom menu "zh_TW" translation

src/levels/mixed/tags.js
Fix a typo in french instructions for exercise Mixed - level 4
=> Fix a typo in Mixed Level 4

src/levels/remote/fetchRebase.js, src/levels/remote/push.js
Hi,
There's another chunk of Polish translation. 
I've found that remote branch on fetchRebase level does not exist. Can you fix it?
=> Polish translation to push and fetchRebase chapters

src/levels/rampup/reversingChanges.js
Fix wrong wording on branch type in reversing changes lesson, italian version
=> Fix italian wording of branch type in reversing changes lesson

src/levels/intro/branching.js
Found a small typo in Polish translation and fixed it.
=> fix: Fix a typo in polish translation

src/levels/intro/branching.js, src/levels/intro/commits.js, src/levels/intro/merging.js, src/levels/remote/clone.js
Hi
This is my first translation on learnGitBranching e my first pull request on GitHub.
=> Italian translation of not translated levels (start with clone.js in remote level)

README.md
Improve / update the instructions for using the level builder. Prompted by the discussion in #897, especially [this comment](https://github.com/pcottle/learnGitBranching/issues/897#issuecomment-983665188).
=> README: improve docs for level builder

src/levels/intro/branching.js
=> feat: add `git switch` Note in chinese site

src/levels/intro/merging.js
Change "sappaimo" to "sappiamo".
=> docs: fix italian typo

.gitignore, src/js/sandbox/commands.js, src/js/views/commandViews.js, src/style/main.css, src/template.index.html
I implemented an auto-complete that reads all commands from getAllCommands() function and suggests the next command based on user input and if you press the tab, the suggested command will be applied.
Feel free to share your comments about the code.
=> autocomplete implemented

src/js/util/debug.js, src/js/views/commandViews.js
=> [AutoComplete] Suggest some commands above others

gulpfile.js, src/template.index.html
You should register Netlify and config like https://github.com/pcottle/learnGitBranching/discussions/932
You can config domain https://learngitbranching.js.org/ for Netlify instead of Github page or make `gh-pages` branch is a sub-folder (https://stackoverflow.com/a/36782614/6250402)
=> build: build for netify

src/levels/intro/branching.js, src/levels/mixed/describe.js, src/levels/mixed/grabbingOneCommit.js, src/levels/mixed/jugglingCommits.js, src/levels/mixed/jugglingCommits2.js, src/levels/mixed/tags.js, src/levels/rampup/interactiveRebase.js, src/levels/rampup/relativeRefs.js, src/levels/rampup/reversingChanges.js, src/levels/rebase/selectiveRebase.js, src/levels/remote/clone.js, src/levels/remote/fetch.js, src/levels/remote/fetchRebase.js, src/levels/remote/pullArgs.js, src/levels/remote/push.js, src/levels/remote/sourceNothing.js
Fixed typos, grammar and readability.
=> Fix Polish translation

src/template.index.html
=> Accessibility: add a label for the textarea

src/js/git/commands.js, src/js/git/index.js
Little attempt at doing #957.
Closes #957.
This probably needs an animation as if it was traversing from HEAD down.
=> add git gc command

src/levels/remote/remoteBranches.js
=> Add: Remote branches are on local, not on the remote repository

src/template.index.html
Hi, I know mobile devices are not officially supported yet, but LGB can work on iPad with external keyboard and this viewport settings change.
You can see the difference in these 2 pictures.
=> Fix viewport settings

src/js/intl/strings.js
Added spanish (es_AR) translation to the HelpBarView
=> helpingWithSpanishTranslation

src/levels/intro/branching.js, src/levels/intro/commits.js, src/levels/intro/merging.js, src/levels/mixed/grabbingOneCommit.js, src/levels/mixed/jugglingCommits.js, src/levels/mixed/tags.js, src/levels/rampup/cherryPick.js, src/levels/rampup/detachedHead.js, src/levels/rampup/interactiveRebase.js, src/levels/rampup/relativeRefs.js, src/levels/rampup/relativeRefs2.js, src/levels/rampup/reversingChanges.js, src/levels/rebase/manyRebases.js, src/levels/rebase/selectiveRebase.js, src/levels/remote/clone.js, src/levels/remote/fakeTeamwork.js, src/levels/remote/fetch.js, src/levels/remote/fetchArgs.js, src/levels/remote/fetchRebase.js, src/levels/remote/mergeManyFeatures.js, src/levels/remote/remoteBranches.js, src/levels/remote/tracking.js
mainly French corrections or rephrasing
but also some modifications of capital letters or brackets
I hope this helps
=> rephrasing and corrections of French version

__tests__/remote.spec.js, src/js/git/commands.js
=> Resolves #1004 -- fix arg parsing on git pull

src/levels/intro/branching.js, src/levels/intro/merging.js, src/levels/intro/rebasing.js
Some minor rewording to reduce confusion.
=> docs: improve polish translation

src/levels/mixed/describe.js
Make one sentence slightly more readable.
=> Slight wording improvement

src/js/react_views/HelperBarView.jsx, src/js/react_views/MainHelperBarView.jsx
Before this PR, the links in the helper bar may have no text. Now the links have the title attributes with these contents: "Show commands", "Show available languages" and "Follow me on Twitter".
=> Accessibility : Links in helper bar now have title attribute

src/levels/remote/pullArgs.js, src/levels/remote/sourceNothing.js
reference: National Institute of Korean Language [explained](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=119871) why '되요' is incorrect.
By the way I deeply enjoyed this game. Thank you.
=> Fix korean translaction

src/js/dialogs/nextLevel.js, src/js/intl/strings.js
I added three exclamation marks where ever needed in the "src/js/dialogs/nextLevel.js" and "src/js/intl/strings.js" files.
=> 'Double Exclamation marks' issue solved!

src/levels/intro/branching.js
=> fix french typo

src/levels/rampup/interactiveRebase.js
Fixed article error: 'le fenêtre' ->  'la fenêtre' -  ('the window').
=> translation -  interactiveRebase.js

src/js/level/index.js
Checking if the level is solved from the LevelStore <br/>
If the level is solved then don't open the dialog box <br/>
Also, stop the final animation of solving if Show Solution is called
=> The confirmation dialog should not open after a user has solved the level (Issue: #1077)

src/levels/remote/remoteBranches.js
The proposed current sentence is a direct translation of the English sentence. Understandable if you know English, but not natural French.
=> Update a french message to make it more natural

src/levels/remote/remoteBranches.js
Deleted repetition of the word "aver" in the Italian translation.
I take this opportunity to thank you immensely for the work you have done which is helping me to better understand how github works in my study path. Sorry if I made some mistakes but English is not my native language and I'm using google translate to write, thanks again for the work you have done and I wish you all the best in your future and future projects.
=> Deleted repetition of the word "aver" in the Italian translation

src/js/dialogs/confirmShowSolution.js, src/js/dialogs/levelBuilder.js, src/js/dialogs/nextLevel.js, src/js/dialogs/sandbox.js, src/js/intl/strings.js, src/js/react_views/IntlHelperBarView.jsx, src/levels/intro/branching.js, src/levels/intro/commits.js, src/levels/intro/merging.js, src/levels/intro/rebasing.js, src/levels/mixed/describe.js, src/levels/remote/push.js
The levels situated below the Intro level and some functionality strings are translated to Turkish.
=> Translation Update: Levels and Functionality Strings in Turkish

__tests__/git.spec.js, src/js/git/commands.js
Added '--create', '-C', and '--force-create' options.
Please let me know if this is wrong or I'm missing something to do.
=> Add switch options

src/levels/mixed/grabbingOneCommit.js, src/levels/mixed/jugglingCommits.js, src/levels/mixed/jugglingCommits2.js, src/levels/mixed/tags.js
Levels Under Mixed (grabbing one commit, juggling commits, juggling commits2, tags) are translated to Turkish
=> Mixed Levels tranlated to Turkish 

src/js/intl/strings.js
Fixed and added some missing pt_BR translations.
=> pt_BR Translations fix and add.

src/js/intl/strings.js
Reverts pcottle/learnGitBranching#1112
=> Revert "pt_BR Translations fix and add."

gulpfile.js
Add listening to jsx type files in js folder in watch mode
=> feat: Gulpfile update

src/js/intl/strings.js
Replays changes from #1112 that were reverted in #1113 and not reintroduced in neither #1114 nor #1117.
I'm not really sure what happened there but at least this way the changes from that first PR don't get lost :)
=> Update pt_BR translations (replay of #1112)

src/levels/remote/fakeTeamwork.js
Translated the remote/fakeTeamwork lesson to es_MX
=> Translate the fakeTeamwork lesson to es_MX

.github/workflows/build-docker.yml
Upgrade actions/upload-artifact for 10x faster build time according to GitHub
https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/
=> Update upload-artifact for faster performance

README.md
This PR adds "Open in Codeanywhere" button to the Readme file, next to the same "Open in Gitpod" button.
Codeanywhere is a cloud-based Integrated Development Environment (IDE) that allows developers to code, learn, build, and collaborate on projects directly from their web browsers. This button opens the Codeanywhere VS Code IDE in the browser, pulls the repo, sets up a container environment and allows the developer to run the code - all of this with a single click and for free.
=> Update README.md with Open in Codeanywhere button

src/levels/remote/fakeTeamwork.js
After performing this exercise, I felt the instructions needed a bit more clarity. I welcome any improvements on top of my suggestion.
=> Update fakeTeamwork.js instructions for clarity

.github/workflows/containerize.yml
=> Use other secret2
