pcottle/learnGitBranching

src/js/intl/strings.js, src/js/react_views/LevelToolbarView.jsx
=> Add translation mechanism for "Objective"

src/levels/remote/fetchRebase.js
There is a typing error in fetchRebase.js file that makes Portuguese translation unavailable for hint.
=> Fix Tranlation issue from Pt-Br in fetchRebase

src/style/main.css
Seems like Firefox requires the height property in order to display the scroll.
=> Fix for #406: scroll for the terminal in Firefox

LICENSE.md
Now that the license file is a markdown file, the license title can be marked accordingly, to make it more conspicuous and convenient.
=> LICENSE.md: format title

src/js/git/commands.js
Modeled after the current implementation of `branch -d` / `branch -D`
Note: since I'm not familiar with the code, this PR is an experimental submission to address #472; if it's successful, it will hopefully illuminate a viable path for me or others to submit follow-up PRs adding the remaining missing aliases, for consistency, as discussed in that issue thread.
=> commands.js: add --force alias to the -f option (fix #472)

src/js/git/commands.js
Addresses #472, follow-up of #473.
=> commands.js: add --all alias to the -a option

src/js/app/index.js, src/js/stores/LocaleStore.js
According to [google documents](https://support.google.com/webmasters/answer/189077)  a site can notify google about alternative locales, using html files of the form:
`<link rel="alternate" hreflang="lang_code"... >` 
This pull request generates such links for each of the locales defined in the LocaleStore and inserts them to the top of <head> element where search engines can find it. (I hope google is smart enough to parse head again after js loads, otherwise this is kind of in vane.)
=> Generate alternate url for different locales so search engine could find them all.

src/levels/mixed/describe.js
The original translation missed this "when you're ready to move on", so I want to add this to the simplified Chinese translation.
=> update zh_cn translation in describe.js

package.json, src/js/app/index.js
We can use `Object.assign` with Node.js 4 or higher.
=> Remove module object-assign

src/style/main.css
Fix #478.
- When we scale browser to 125%
- Fixed  `#terminal`  will overlay `commandLineBar` if `#terminal` is long.
- Avoid display 900px in small screen
=> Fixed some css wrong

src/style/main.css
In firefox, we can't see all of dialog select level (#474 )
After fixed it:
=> fix(css): fix offset top of select level (in firefox)

.gitpod.yml
Follow-up improvement to #546.
@pcottle I'm also happy to add an `echo` command as suggested in https://github.com/pcottle/learnGitBranching/pull/546#issuecomment-467761064 if you think that's a good idea.
Please take a look when you have time.
=> Use 'grunt fastBuild' in Gitpod to build the app faster

.gitpod.yml
This implements https://github.com/pcottle/learnGitBranching/pull/546#issuecomment-467761064 as requested in https://github.com/pcottle/learnGitBranching/pull/548#issuecomment-467972574.
Here is what it looks like (see the two additional lines printed in the Terminal):
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/jankeromnes/learnGitBranching/blob/master/src/js/git/index.js)
Please let me know if you like the wording, or how it can be improved.
Notes:
- I used `printf` instead of `echo` as it's generally safer with escaped characters and CLI options across various shells
- I've disabled `python3 -m http.server 8000`'s error output, as it was printing new lines on every served resource, thus quickly hiding the message
Another option …
=> Print helpful welcome message in Gitpod

package.json
Fix error can't find `grunt`.
When I install with : `npm i` to install dependencies and devDependencies, It don't add bin for `grunt` (e7b7a8d removed `grunt-cli`).
If you install with Yarn, it is ok because `yarn.lock` have `grunt-cli` (if you remove yarn.lock and re-install, we will don't have `grunt-cli`).
`grunt` has bin file in new version so my recommend is update `grunt`.
=> Update `grunt` version

.travis.yml
This project uses `contributor-faces`, it includes `gh-got`.
And `gh-got` require Node v8 so `travis-ci` will have the error.
So I have 2 option:
- Remove Nodejs v7 in `.travis.yml` (merge this pull request if you choose this way)
- Or install `contributor-faces` in your machine(require Node >= 8) and sometimes run `contributor-faces .` in your project to update list contributor(if you choose this way, you should reject this pull request and remove `contributor-faces` in `package.json`)
Or you can remove `contributor-faces` and use another way.
=> remove Node.js v7 in travis-ci

__tests__/git.spec.js, src/js/git/index.js
Currently the range operator (e.g. "master..future") is misinterpreted as a relative ref, due to a regex which strips off everything from the dots onwards. As a result, "master..future" is interpreted as just "master". Because the regex is not strict, many other illegal forms are also misinterpreted as relative refs, such as "master&&&".
This PR adds "$" (zero-length line terminator) to the end of the regex, forcing the regex to match the whole argument. This way, if the argument is not actually a relative ref, it will not be interpreted as such. The result will be an error ("The ref master..future does not exist or is unknown"), which I think is preferable to the current behavior.
See #561
=> Explicitly fail when unsupported range operator is specified

src/js/graph/treeCompare.js, src/js/stores/LevelStore.js
You use `_.uniq` but don't return value of `_.uniq`.
You use that function to check `result` value so my recommendation is to use `every`, it will break if the value of callback `false` to avoid call other callback when `result` is `false`
And I remove one line call `underscore` but don't call `_`
=> chore: use `every` instead of `uniq`

__tests__/base.js, __tests__/git.spec.js, src/js/git/commands.js, src/js/git/headless.js, src/js/git/index.js, src/js/models/commandModel.js
This is the first step in adding greater support for revision ranges (see #561). Currently, only log supports revision ranges, it only supports specific kinds (single tip includes and excludes), and only in very limited formats ("git log include" or "git log include ^exclude"). With this PR, log now supports any number of single tip includes or excludes, in any order, as real git does.
This PR also introduces support for the "rev-list" command, which uses the same revision range capability. In addition to increased git compatibility, the rev-list command also provides much simpler output with which to test the output ordering of revision ranges.
Compatibility Note: this PR changes the output ordering of the log command. The previous ordering was essentially a breadth-first search. The new …
=> More robust support for revision ranges

__tests__/git.spec.js, src/js/git/index.js
This PR adds support for the range operator ("branchA..branchB") to the `log` and `rev-list` commands.
It also refactors revision specifier processing into a "pipeline" model, to make it easier to support new kinds of specifiers.
See #561
=> Range operator

Gruntfile.js, package.json, src/js/app/index.js, src/js/level/index.js, src/js/react_views/CommandHistoryView.jsx, src/js/react_views/CommandView.jsx, src/js/react_views/CommandsHelperBarView.jsx, src/js/react_views/HelperBarView.jsx, src/js/react_views/IntlHelperBarView.jsx, src/js/react_views/LevelToolbarView.jsx, src/js/react_views/MainHelperBarView.jsx, src/js/visuals/animation/index.js, src/js/visuals/visualization.js
- Up to date some `dependencies`
- Use `grunt-contrib-uglify-es` instead of `grunt-contrib-uglify`
- Add module `react-dom` to render, `react@16.8.6` move `render` to `react-dom`
- Add module `fbjs` to call `fbjs/lib/keyMirror`
- Add `https:` to cdn link.
- And some small fix error when change old to new version.
=> Up to date dependencies and migrate old function of `react`

.travis.yml, checkgit.sh
If dependencies are changed (in package.json) without updating the yarn.lock
file, or if any other part of the build process starts producing unignored
files, the CI build will fail, so that the problem can be corrected before the
PR is merged.
See #575
=> Check that there are no source file changes before building

Gruntfile.js, package.json, yarn.lock
- [DEPRECATED] `grunt-react` and they notice `Please use grunt-babel instead`
- But you use `grunt-react` for transform `browserify` so I use `babelify` instead
=> Use `babelify` instead of `grunt-react`

.gitpod.yml, README.md
This change fixes the the Gitpod demo by setting the `yarn` global prefix to `/workspace/.yarn`, and adding it to the `PATH` env variable.
Follow-up to https://github.com/pcottle/learnGitBranching/issues/574#issuecomment-490173208.
Note: The `before` step runs both during Gitpod's first workspace start (`before && init && command`) and subsequent restarts (`before && command`). More info [here](https://www.gitpod.io/docs/44_Config_Start_Tasks/#code-classlanguage-textbeforecode-command).
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/jankeromnes/learnGitBranching/blob/patch-1/src/js/git/index.js)
=> Use `yarn grunt` instead of the global `grunt`

src/js/react_views/IntlHelperBarView.jsx
rename es_AR to argentino
but leave it as the default for Spanish
since es_ES is not fully translated
Fixes #528
=> feat: make es_ES available from the languages menu

src/js/git/commands.js, src/js/git/index.js, src/js/visuals/index.js
Added the tag-deleting feature and fixed a bug, where the duplicate tag-name wouldn't show in the error message
=> added git tag -d <tag> and  fixed error message

src/js/git/commands.js
Fixed a small typo in the error message displayed in the console when 'origin' is not specified.
=> Fixed typo in error message displayed

src/js/intl/strings.js
The name of the branch doesn't correspond at all with the commit. The "french git rebase" has been fixed in replacing a value in the strings by the good one.
When typing "git rebase" in the command line, we have to refresh the page to reuse the application.
=> Change upper value in 'git-error-args-few' string to lower

src/js/sandbox/commands.js
#608 
Before:
- Why don't use `\b`: `ls-test`
I checked `$` in end of line
After:
=> fix: get `ls` and `cd` with right way

src/levels/remote/sourceNothing.js
Despite the hint to the contrary, `git branch` is not disabled here. Since `git checkout -b` also works here, I disabled them both.
=> Disable "git branch" and "git checkout" in source nothing level (remoteAdvanced7)

src/levels/rampup/detachedHead.js
The instructions for level rampup1 say to "...detach HEAD from bugFix and attach it to the commit instead..." HEAD in this level points to the master branch at the start. I changed the starting target of HEAD from master to bugFix to reflect these instructions.
=> Change where HEAD points to match objective

src/js/dialogs/nextLevel.js
It is better with `;` or `.`, not both.
Or you can use `.` instead of `;` ( same the normal sentence)
=> fix(typo): remove unnecessary `.`

src/levels/remote/lockedMaster.js
Hi Peter,
first of all, I'd like to thank you for creating such an amazing interactive git tutorial. I'm just in the process of getting familiar with using git and github. So far I've really enjoyed using learnGitBranching.
As I've come across the "locked master" level, I've noticed that there is currently no german translation available. Since I'm a native german speaker, I thought it would be a great opportunity to implement the german translation for this level and in the process get a little exercise in using git/github. Please bare with me here if I made any mistakes submitting change requests, or writting the translation. I'm not familiar with writting javascript, since I'm coming more from the embedded systems department - hope the translation implementation is still correct. …
=> Implemented german translation of lockedMaster level.

package.json, src/js/react_views/CommandView.jsx, yarn.lock
You created `src/js/util/keyMirror.js` in [88614aa](https://github.com/pcottle/learnGitBranching/commit/88614aac06bb1d256195e99223de566373839ba1#diff-936ff0cfd8c6362334eb9861a94fe879R7).
=> refactor: use existing `keyMirror`

gulpfile.js, src/js/stores/LevelStore.js
Related #661
I assign `var localStorage` inside if-block(not called) so `localStorage` doesn't refer to `window.localStorage`.
BTW, fix the report by JSHint.
=> fix: keep `localStorage`

src/js/react_views/CommandView.jsx
When you destroy command with [`toDestroy[i].destroy();`](https://github.com/pcottle/learnGitBranching/blob/699d5ffb71f197885a7a585b88ce11546d04d6c8/src/js/react_views/CommandHistoryView.jsx#L94), `CommandHistoryView`'s props will 
change and render its child(`CommandView`)
In my opinion, we don't need to unmount it(react do it)
and pass this error
=> fix: `CommandView` don't need to unmount itself

src/levels/intro/merging.js
bugFix is the parent of master, not its child. master is "descendant"
of bugFix, not the reverse.
I use "ancêtre", as other latin langage translaton, instead.
"parent" exists in French but is ambiguous, and have broader
and narrower contextual meanings (respectively, any relative, eg. cousins,
or just father and mother).
=> Bug: reverse meaning in French

src/js/visuals/index.js, src/js/visuals/visBranch.js, src/js/visuals/visNode.js, src/js/visuals/visTag.js
Thanks for the great tool.
This PR tries to add proper default fonts for Windows and Linux. The font list is based on [what VSCode chooses](https://github.com/microsoft/vscode/blob/466da1c9013c624140f6d1473b23a870abc82d44/src/vs/editor/common/config/editorOptions.ts#L3464-L3466).
(I believe it is really rare for a terminal to use `Courier` as the default font.)
=> 💄 Choose proper fonts for all 3 OSes

src/js/level/builder.js
As discussed [here](https://github.com/pcottle/learnGitBranching/issues/187), editing an existing level was broken, e.g. `build level intro3`, resulted in an error `Uncaught Error: need goal tree and solution`. After debugging, the problem seemed to be that editLevelJSON was never assigned and when the level editor started, the level object was empty.
=> Fix: Editing an existing level was broken

src/style/main.css
Shells usually have a space character on their prompt after the "$" or "#"
=> increase margin-left for "shell input"

src/js/intl/strings.js
Hi,
I found your Tool very helpful for learning the git basics, so i thought i put my newfound skills to good use and fix some typos in the german version :-) 
The german version contained the wrong articles and some prepositions for Level".
Hope this Pull Request is not totally stupid, out of place or in any other way "wrong".
=> fixed typos in german containing "Level"

src/levels/remote/tracking.js
Hi,
found a small typo in the german translation.
=> Fixed a small typo in the german version of 'remote tracking'

src/template.index.html
As mentioned in #746, I think it might be neat if we changed the "Fork me on GitHub" ribbon into a GitHub Corner, instead.
=> Close #746 by changing GitHub ribbon to a corner

README.md, src/style/main.css
I am sending a small amendment, where currently the "exit from the menu" icon is not visible in languages (I send current and corrected views)
Plus I added myself to the README;)
Actual:
After the amendment:
PS. I restored the box width to the width before my corrections were uploaded ... that is from 520px to 500px
=> Fix css + I in README

src/levels/intro/branching.js, src/style/main.css
It's just a suggestion ... the link instead of opening in the same window to interrupt the "fun", opens here in a separate window. HTML was used because in Markdown, there is no option to open in a new window (I didn't find that information at least).
=> [suggestion]change link with attribute target="_ blank"

src/js/git/index.js
'\n' causes the `git log` and `git show` messages showing with paragraph tags every line
Replace '\n' with '\<br/>' (without affecting the original display) so as to get rid of '\<p>' tags with every line, and avoid to directly write the template in the function.
As a result, one commit log is shown in one paragraph tag for now.
=> Fix multiple paragraph tags of 'log' and 'show'

src/style/main.css
- The title bar of floating windows that can be dragged (e.g. the "Goal To Reach" ones) now shows a "grab" cursor when hovered, and a "grabbing" cursor when being dragged.
- The buttons in those windows, which are clickable, now show the `pointer` (hand) cursor, instead of the `default` (regular arrow) cursor.
This PR was inspired by #439 (but is, AFAIK, unrelated to it).
=> Improve styles for interactive pop-up windows

src/template.index.html
Hi! 
LearnGitBranching is a really, really great tool to learn Git, and I was very disappointed with the full-page ribbon on Firefox at my work place.
I'm not sure what was the "above" proposed solution on issue #758 (removing the ribbon apart) but setting `height: 7vmin` in CSS style instead of HTML `height` attribute seems to do the job both on Firefox 68 (on work-place Ubuntu variant) and 78 (on Debian 10).
Tested successfully with preview at https://8000-dad7cab5-4dc7-4381-9974-63b28d28edbc.ws-eu03.gitpod.io
=> Resolves #758 - Set github-corner height in CSS style instead of HTML attribute

src/style/main.css
As for me, it will look better without a border for `code`, but it's up to you :wink:
=> Fix text falling out in the main popup

src/js/intl/strings.js
This is the greatest tutorial about git branching!
I found out that some sentences are not translated in Traditional Chinese in interactive rebase dialog and command console.
Update the missing sentences.
=> Translate missing sentences in zh_tw.

README.md
Hi!
I noticed that the project demo gif is a bit old - it is showing "master" insteadof "main", github badge insteadof triangle in the corner etc.
Do you like the new version? Or do you want it more sharp, or ...?
Btw. I added myself to a contributors list.
Best regards
=> New demo.gif

src/js/git/index.js
fixes #804 and the overall issue of "git branch" command using "master" instead of "main"
*although I would note that an even better solution would be to gut the use of "master" from the repo so as to reduce confusion
=> switching use of master to main in git branch cmd

src/js/visuals/visBranch.js
This adds a regex to replace 'master' with 'main' in the command line output when checking out main by clicking on the tag with the branch name.
Resolves issue #821.
FYI: @pcottle - as we discussed in the issue comments, I wasn't able to build the app to test this change
=> change master to main in CLI output when checking out via click

src/levels/remote/pushArgs.js, src/levels/remote/sourceNothing.js
This PR disables `git switch` for levels where `git checkout` is disabled.
=> Disable 'git switch' along with 'git checkout'

src/js/dialogs/sandbox.js
Fixes the old default branch 'master' deleting the repetition of the branch 'main' which substitutes it
=> Fix typo in italian intro dialog version

src/levels/intro/commits.js
Fixed typo in polish translation.
=> Fix polish typo 'rewiznajch' to 'rewizjach'

src/levels/rampup/detachedHead.js
Change "maggiorparte" to "maggior parte".
=> docs: fix italian typo

src/js/views/commandViews.js
Typing: `git   <multi-space here>     comm` in terminal:
Expected:
Support multiple command (split by `;`):
Currently, press  <kbd>tab</kbd> to replace the shadow content terminal, it must be not empty.
=> fix: autocomplete show right shadow content and support multiple command

src/style/main.css, src/template.index.html
Part of #960.
---
This is WIP in that only a single button was fixed so far (the first OK button).
With this approach, there should be no visual difference. The button is now keyboard focusable and accessible with screen readers. With macOS VoiceOver, when navigating to the button, it says "OK, button".
=> Accessibility: use buttons

src/levels/remote/clone.js, yarn.lock
Phabricator is no longer being maintained and new hosted instances may not be created since June 1, 2021: https://admin.phacility.com/phame/post/view/11/phacility_is_winding_down_operations/
=> Remove Phabricator example link as it is no longer supported

README.md
Click Gitpod link can't find the file,  `master` had changed to `main`
=> Fix Gitpod Link

src/style/main.css
As the discussion in #1003, add a CSS rules to avoid the goal tree over the goal window in shorter display.
=> fix: nodes over window in short display

src/js/react_views/CommandView.jsx, src/style/main.css
Part of #960
Changed the tags of elements in the terminal : the elements are now live regions.
=> Accessibility : Output elements

src/js/views/index.js
Part of #960 
In order to contribute to the issue of zcorpan, I corrected one of the points present in the to-do list :
> Content outside modal dialog boxes are not inert and so can be reached with screen readers. <dialog>.showModal() could help (or maybe the inert attribute).
In this PR, when a modal is opened, all children except .modalView have the attribute "inert" (as zcorpan suggested), which is removed when the modal is closed.
=> Accessibility : Inert attribute for content outside of modal

src/js/views/levelDropdownView.js, src/style/main.css, src/template.index.html
Part of issue #960
Replaced div elements to links with "#" as `href` value. 
I checked on my side, no problem has been created with this modification.
=> Accessibility: Level links are now links

__tests__/git.spec.js, src/js/git/commands.js, src/js/git/index.js
Being a popular option in Github to squash and merge, it would be interesting to add support for this option.
**Initial scenario**
After running `git checkout -b feat;git commit;git checkout main;`
```
C2 (feat)
C1 (main) *
```
**With `merge --no-ff`**
After running `git merge --no-ff feat`
```
C2 (feat) ─┐
C1 ────────┴─ C3 (main) *
```
**With `merge --squash`**
After running `git merge --squash feat`
```
C2 (feat)
C1 ────────── C3 (main) *
```
This equivalent to just `git commit -m "Squashed merge branch 'feat' into 'main'"` as the connection with the C2 node is lost, and further `git branch -D feat` will leave C2 being not connected and ready to prune. This will show how you destroy history by using squash.
=> Add support for `git merge --squash {branch}`

src/js/views/gitDemonstrationView.js, src/style/main.css, src/template.index.html
Waiting for comment, all tests passed.
I will add tests for this feature after it's approval.
=> #937 - Solution proposal

src/levels/remote/clone.js, src/levels/remote/push.js
Markdown link being displayed incorrectly.
=> Fix incorrent markdown format in zh_TW

__tests__/remote.spec.js, src/js/git/commands.js
Adds the delete flag as a method to delete remote branches
`git push origin -d foo`
uses the existing method of deleting remote branches by colon refspec
=> Added delete flag to 'push' command to delete remote branches

__tests__/git.spec.js, src/js/git/index.js
Fixes issue #977, the breadth first search already has the commits in the order of tree hierarchy just in reverse.
Added the test case from the issue
=> Rebase update

__tests__/remote.spec.js, src/js/git/commands.js, src/js/git/index.js
- Adds `git merge(M|P)R <source_branch> <target_branch> [--delete-after-merge]` command to simulate a Merge/Pull Request being merged into the target branch
- The optional flag `--delete-after-merge` will remove the merged branch on the origin tree
- The local remote branch remains as it is Git default behavior, even after `git fetch` (it would require `git fetch --prune` support to automatically prune remote tracking branches)
- You can push a branch with a deleted remote tracking branch on origin, the ref will just update.
Resolves #1057
```sh
git clone;
git switch -c feat;
git commit;
git push;
git fakeTeamwork;
git mergeMR feat main;
```
```sh
git clone;
git switch -c feat;
git commit;
git push;
git fakeTeamwork;
git mergeMR feat main --delete-after-merge;
```
If you `git fetch` after …
=> feat: command to simulate Merge/Pull Request

src/js/app/index.js
This resolves the issue #1139 I just created, about permalink to levels.
I did not add unit tests as I didn't find anywhere query arguments are tested. But I've manually tested my changes through Gitpod (which is simply amazing !).
I also was thinking about a "share level" feature, but:
- this another feature
- this is out of scope of the initial issue
- this can have many implementations possible, and different UI design too
- this idea would need your validation first, before any change
Feel free to let me know what you think about all this.
=> Resolves #1139: can use a direct permalink to a specific level

src/js/views/index.js
This chage allows you to move the modal that comes up when doing an interactive rebase.
I think this is useful when you want to work on a modal while looking at the goal. (ex. level2 move2)
- before
- after
=> make modal draggable

src/levels/rampup/relativeRefs.js
I've successfully fixed the bug! Now, the bugFix branch will be displayed as the active branch instead of main.
Before :
After:
=> fix: :bug: made bugFix branch an active branch insted of main

__tests__/LevelStore.spec.js, src/js/actions/LevelActions.js, src/js/level/index.js, src/js/stores/LevelStore.js, src/js/views/levelDropdownView.js, src/style/main.css
This feature introduces the ability to track and record the user's best performance on each level. By storing both the completion status (solved) and whether the user achieved the best possible outcome (best), the application can provide more detailed feedback and track user improvement over time.
=> feature: perfection tracker for levels with best number of commands

src/style/main.css, src/template.index.html
As your suggestion, added new functionality to display a star icon for "best" completed levels in the level selection interface. I tried to  maintain the existing styling and hover states while avoiding the use of modern selectors like :not() for better backwards compatibility.
=> css improvements and star icon

src/levels/rampup/cherryPick.js
I have translated the cherryPick.js file into Turkish to make it more accessible to Turkish-speaking developers. All the content in the file has been carefully translated, ensuring clarity and maintaining the original meaning.
Please review the translation and let me know if any adjustments are needed.
=> cherryPick.js translated to turkish

src/levels/intro/rebasing.js
Move the result instructions from the beforeMarkdown to the afterMarkdown array.
=> fix(rebasing.js): fix the order of instructions displayed in french version

src/js/react_views/IntlHelperBarView.jsx
Standardized language names to be written in their native form (e.g., "Italiano" instead of "italiano," "italian," or "italy").
=> Fix: Renaming locale labels

generatedDocs/levels.html, src/levels/intro/rebasing.js
While going through the Git lessons, I found a wording issue in the message displayed during the Intro 4 level, right after rebasing onto the **`main`** branch.
The original message said:
> “Awesome! Now the work from our bugFix branch is right on top of main...”
However, since the rebase places the **`bugFix`** commits beneath the latest **`main`** commits to maintain a linear history, I’ve updated the message for clarity:
> “Awesome! Now the work from our bugFix branch is right beneath main...”
This should better reflect the actual commit structure post-rebase.
=> Updated Demonstration Message for Intro4

src/js/git/index.js
=> My attempt at #1245

src/js/dialogs/confirmShowSolution.js, src/js/dialogs/levelBuilder.js, src/js/dialogs/sandbox.js, src/js/intl/strings.js, src/levels/index.js
Changing the current de_DE (german) translated strings for better representation as the currently implemented german translation feels a bit weird.
There are no code changes, only string changes - merging the branch should probably not take much time / effort.
Regards
Ben
=> Changing strings for better representation

src/levels/intro/merging.js
The English description is:
`Each commit turns a color that is the blended combination of all the branches that contain that commit.`
Which was inaccurately translated into:
`Jeder Merge Commit bekommt als Farbe eine Mischung aus den Farben seiner Vorgänger.`
The German translation implies that the new commit color is a combination of it's previous (parent) commit colors which is not the case. The new translation improves the intended meaning.
=> fix: improve inaccurate German translation of commit color rules

generatedDocs/levels.html, src/js/git/index.js, src/levels/mixed/describe.js
git describe output uses hyphens (-) not underscores (_).
=> fix git describe output format (underscore -> hyphen)
